### ISSUE TITLE
Not handling response properly

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/ui-dbscan-clusterer#1]
We're having trouble getting this UI to display the output, and think the problem lies in these lines.

https://github.com/disarm-platform/ui-dbscan-clusterer/blob/4fce975e26b04bbc54a7e46bab4a3065088a46ab/server.R#L62-L66

Think there are two problems:
1. We're just returning the `response` from the API request, without checking its status (whether successful, etc). We should add some checking here, and show a clear error to the user if the API failed.
2. I think the functions which use this `response` are expecting it to be a `list` type of the _body_, but I think that a) `return(response)` sends back the whole request response, b) not certain it is a `list`.

**Comment by onlyjsmith** [comment]
Just seen the following in `ui-raster-vector...`, which looks like the code we're missing in this repo:

```r
    response <-
      httr::POST(
        url = "https://faas.srv.disarm.io/function/fn-raster-vector-summary-stats",
        body = as.json(input_data_list),
        content_type_json(),
        timeout(90)
      )
    
    # Check status
    if (response$status_code != 200) {
      stop('Sorry, there was a problem with your request - check your inputs and try again')
    }
    
    # Return geojson as sf object
    response_content <- content(response)
    return(st_read(as.json(response_content$result)))
```

**Comment by HughSt** [comment]
OK dealt with and pushed (this time!)
