### ISSUE TITLE
UI doesn't work with test_req.json (parcel-by problem?)

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/ui-dbscan-clusterer#4]
We _can_ get it it to work with subject as `https://www.dropbox.com/s/rqi9er0ehy0yfo5/build_crop.geojson?dl=1`, rest as default values.

But when we add anything to parcel by, it crashes with red error message
<img width="565" alt="Screenshot 2019-04-02 14 53 35" src="https://user-images.githubusercontent.com/148280/55404743-de812780-5558-11e9-9e89-34a2bb644a14.png">

Checking the Shinyapps logs I don't see anything obvious.

**Comment by HughSt** [comment]
Can you give me a URL for a file which causes it to crash? It works for me with the test_req parcel file

`https://www.dropbox.com/s/l97za3w75ts2qrc/osm_roads_swz_crop.geojson?dl=1`

**Comment by onlyjsmith** [comment]
That one! I tried with `https://www.dropbox.com/s/l97za3w75ts2qrc/osm_roads_swz_crop.geojson?dl=1` and it crashed.

**Comment by HughSt** [comment]
Assuming you are trying via the hosted shiny app? Can you try again - I just tried and it worked fine

**Comment by onlyjsmith** [comment]
Sure! Yes, was hosted Shinyapp.

**Comment by onlyjsmith** [comment]
Hmm. It works.

That's good, but we tried about 10 times between us earlier and could not get a reliable response - I mostly got errors...

Have you redeployed it?

**Comment by onlyjsmith** [comment]
And it's just errored. The exact same request.

**Comment by onlyjsmith** [comment]
I'll check the fn server logs in case its timing-out.

And now it worked: both with that single parcel-by, and also all three from test_req

**Comment by onlyjsmith** [comment]
I think I had a broken URL in my auto-suggest on the input box - it looked the same as `https://www.dropbox.com/s/l97za3w75ts2qrc/osm_roads_swz_crop.geojson?dl=1`, but was actually different... 

Is more user-error by me than a bug, but still a nasty one to catch. Sorry!

I've had a few more successes since I cleared out the auto-suggest box. Let's close this - will reopen if I have a new reproducible case.

**Comment by onlyjsmith** [comment]
@HughSt @TNgidi maybe something to learn here though - we might want to make to print out the complete request we get in each UI.

This screenshot is what I was looking at. The pink-ringed section had the incorrect URL being sent, but from a glance it looks fine.

![image](https://user-images.githubusercontent.com/148280/55409588-9404a880-5562-11e9-994b-133ac429b8e5.png)

**Comment by HughSt** [comment]
What about adding a `download request` button which users could look at and/or send to us?
